---
swagger: '2.0'
info:
  title: fuzzy-engine
  version: 0.1.0
host: desolate-fjord-55589.herokuapp.com
schemes:
- https
paths:
  "/v1/demographics":
    get:
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              "$ref": "#/definitions/Demographic"
definitions:
  Demographic:
    type: object
    properties:
      height:
        type: number
      weight:
        type: number
      dob:
        type: string
      admit_source:
        type: string
        enum:
        - EMERGENCY
        - ROUTINE
        - TRANSFER
      admit_type:
        type: string
        enum:
        - Emergency
        - Routine
        - Pregnancy
        - Urgent
      provider_name:
        type: string
      provider_phone:
        type: string
      hospital:
        type: string
        enum:
        - HUP
        - PAH
        - PMC
      first_name:
        type: string
      last_name:
        type: string
      visit_number:
        type: integer
      service:
        type: string
        enum:
        - ORTHOPEDICS
        - EMERGENCY_DEPARTMENT
        - HOSPITALIST
        - CARDIOVASCULAR_MEDICINE
        - OBSTETRICS
        - MEDICINE
        - ONCOLOGY
        - CARDIAC_SURGERY
        - PULMONARY
        - GASTROENTEROLOGY
      race:
        type: string
        enum:
        - White
        - Black
        - Unknown
        - Asian
        - Hispanic
        - Other
      gender:
        type: string
        enum:
        - Male
        - Female
        - Unknown
      marital_status:
        type: string
        enum:
        - Single
        - Married
        - Widowed
        - Divorced
        - Unknown
